# Generated by Django 5.1.4 on 2025-01-03 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('esta_activa', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_completo', models.BooleanField(default=False)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=128)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=128)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.envio')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.opcion')),
            ],
        ),
    ]
